--Q1.what is the total revenue generated by male vs female customer
select gender,sum(purchase_amount) as revenue
from customer
group by gender

--Q2.which customer used a discount but still spent more than the average purchase amount
select customer_id,purchase_amount
from customer
where discount_applied = 'yes' and purchase_amount >= (select avg(purchase_amount) from customer)

--Q3.which are the top5 products with the higest average review rating?
select item_purchased, round(avg(review_rating::numeric),2) as  "average product rating"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5;


--Q4 compare the average purachae amounts between standard and ewpress shipping.
select shipping_type,
avg(purchase_amount)
from customer
where shipping_type in ('Standard','Express')
group by shipping_type

--5Q do subscribed customers spend more? compare average spend and total revenue between subscribers and non- subscribers.
select subscription_status,
count(customer_id) as total_customers,
round(avg(purchase_amount),2) as avg_spend,
round(sum(purchase_amount),2) as total_revenue
from customer
group by subscription_status
order by total_revenue, avg_spend desc;

--6Q which 5 products have teh highest percentage of purchase with discounts applied?
SELECT item_purchased,
       ROUND(100 * SUM(CASE WHEN discount_applied = 'yes' THEN 1 ELSE 0 END) / COUNT(*), 2) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

--7Q segment customer into new,returning, and loyal based on their total
--number of previous purchases and show teh count of each segement.
WITH customer_type AS (
    SELECT customer_id,
           previous_purchases,
           CASE
               WHEN previous_purchases = 1 THEN 'new'
               WHEN previous_purchases BETWEEN 2 AND 10 THEN 'returning'
               ELSE 'loyal'
           END AS custom_segment
    FROM customer
)
SELECT custom_segment AS customer_segment,
       COUNT(*) AS "number of customers"
FROM customer_type
GROUP BY custom_segment;

--8.what are the top3 most purchased products within each category?
WITH item_counts AS (
    SELECT 
        category,
        item_purchased,
        COUNT(customer_id) AS total_orders,
        ROW_NUMBER() OVER (
            PARTITION BY category 
            ORDER BY COUNT(customer_id) DESC
        ) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)
SELECT 
    item_rank,
    category,
    item_purchased,
    total_orders
FROM item_counts
WHERE item_rank < 3;

)

--9Q are customers who are repear buyers (more than 5 purchases ) also likely to subscribe?
select subscription_status,
count(customer_id)as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status


--10 what is the revenue contribution of each age group?
select age_group,
sum(purchase_amount)as total_revenue
from customer
group by age_group
order by total_revenue desc;
